import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Providers } from "./providers"
import NavBar from "@/components/navbar/NavBar"
import NavBarMobile from "@/components/navbar/NavBarMobile"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar />
          <NavBarMobile />
          {children}
        </Providers>
      </body>
    </html>
  )
}
